In [1]:
import numpy as np

# Datatypes and Attributes

### Numpy's main data type is NDarray

In [3]:
a1 = np.array([1,3,2,4,5,6,7,8,9])

In [7]:
type(a1)

numpy.ndarray

In [8]:
a1.size

9

In [13]:
a4 = np.ones((2,3), dtype=int)

In [15]:
a4.dtype

dtype('int64')

In [16]:
a5 = np.zeros((2,3),dtype=int)

In [17]:
a5

array([[0, 0, 0],
       [0, 0, 0]])

In [22]:
range_array = np.arange(1,10,2)
range_array

array([1, 3, 5, 7, 9])

In [30]:
random_array = np.random.randint(0,50,size=(2,3))

In [31]:
random_array

array([[ 3, 27, 43],
       [22, 40, 45]])

In [32]:
random_array[-2] // 3**2

array([0, 3, 4])

In [33]:
a99 = np.array([4,5,6,7,8,9,8,76,5,45,33,2])

In [34]:
a99.shape

(12,)

In [41]:
a99 = a99.reshape((2,6))

In [47]:
a99.T

array([[ 4,  8],
       [ 5, 76],
       [ 6,  5],
       [ 7, 45],
       [ 8, 33],
       [ 9,  2]])