In [3]:
# Fiting the model on our data and use it to make predictions
import numpy as np
import pandas as pd

X = Features, Features variable

Y = label, target, target variable

In [4]:
hd = pd.read_csv('heart-disease.csv')

In [7]:
# Importing RandomForestClassifier 
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
np.random.seed(42)
# make the data

X = hd.drop('target',axis=1)
y = hd['target']

X_train, X_test, y_train,y_test = train_test_split(X,y,test_size=0.2)
clf = RandomForestClassifier()
clf.fit(X_train,y_train)
clf.score(X_test,y_test)

0.8524590163934426

## Making Predictions using Machine Learning Model

In [8]:
# Use trained model to make predictions

There are two ways to make predictions

    1. 'predict()'
    
    2. 'predict_proba()'

In [9]:
clf.predict(X_test)

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [10]:
y_preds = clf.predict(X_test)
np.mean(y_test == y_preds)

0.8524590163934426

'predict_proba()' returns probabilities of a classification label

In [12]:
clf.predict_proba(X_test[:5])
# [0.89, 0.11] means there is probaility of 0.89 of heart disease and 0.11 of not heart disease

array([[0.89, 0.11],
       [0.49, 0.51],
       [0.43, 0.57],
       [0.84, 0.16],
       [0.18, 0.82]])

In [18]:
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()
# housing # gets downloaded as dictionary
housing_df = pd.DataFrame(housing["data"], columns=housing["feature_names"])
housing_df["target"] = pd.Series(housing["target"])
housing_df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  target  
0    -122.23   4.526  
1    -122.22   3.585  
2    -122.24   3.521  
3    -122.25   3.413  
4    -122.25   3.422

In [19]:
from sklearn.ensemble import RandomForestRegressor

In [21]:
np.random.seed(42)
# create the data
X = housing_df.drop('target', axis=1)
y = housing_df['target']
# split into train and test
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)
# create model instance
model = RandomForestRegressor()
# fit the model to data
model.fit(X_train,y_train)
# make prediction
y_preds = model.predict(X_test)


In [22]:
y_preds[:10]

array([0.49384  , 0.75494  , 4.9285964, 2.54029  , 2.33176  , 1.6549701,
       2.34323  , 1.66182  , 2.47489  , 4.8344779])

In [25]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test,y_preds)
# the output value means ,each one of our model predictions is 0.32 different to the actual test value

0.3265721842781009